container:
  image: l.gcr.io/google/bazel:latest
task:
  build_script: bazel build
    --spawn_strategy=sandboxed
    --strategy=Javac=sandboxed
    --genrule_strategy=sandboxed
    --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
    //...
