container:
  image: l.gcr.io/google/bazel:latest
task:
  build_and_test_script: bazel test
    --spawn_strategy=sandboxed
    --strategy=Javac=sandboxed
    --genrule_strategy=sandboxed
    --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
    //...
